### PR TITLE
publish The Engula Community Project

### PR DESCRIPTION
**Pull request by tisonkun**
Signed-off-by: tison <wander4096@gmail.com>

### CODE REVIEW

**Comment by huachaohuang** [comment]
@tisonkun Thanks for initiating the community project. I will need some time to think it over before making this big commitment. Then I will go through the details.

**Comment by tisonkun** [comment]
@huachaohuang here is a reminder and may I ask what schedule you plan to review this post?

**Comment by huachaohuang** [comment]
@tisonkun How about we postpone this after the release of v0.2? I have to say I can't decide it on my own.

**Comment by huachaohuang** [comment]
Besides, I am not comfortable announcing something like this before we get much done.

**Comment by tisonkun** [comment]
@huachaohuang thanks for your updates. Make sense to me.

**Comment by tisonkun** [comment]
@huachaohuang if you can find a time to share what points you think undetermined commitments, and who else should be involved to make the decision, it will help me understand and consider the content and process better.

**Comment by huachaohuang** [comment]
@tisonkun My first concern is about the necessity of making an official community project and announcing it. It's nice to have some guidelines and practices to build the community. But I prefer forming the community naturally for a while. Or if necessary, we can put a simpler description in the engula repo (for example, CONTRIBUTING.md or dev guide) to set the tone.

**Comment by tisonkun** [comment]
@huachaohuang thanks for your reply! After a few considerations, I realize that the original purpose of this project isn't making a commitment - it's about principles I propose us, contributors, to follow.

I agree to settle down principles along with the community growth, and it should ease the burden of reviewing specific items. For the community report, if we're focusing on v0.2 in months, we also don't have to post such one.

Closed as it's always an unofficial reference which we can refer to when facing challenges. I'll try to integrate concrete items into our dev guide later.

**Comment by huachaohuang** [comment]
@tisonkun Thanks for your understanding and your support for the community!

**Pull request closed without merging**
